hugo:
  image: jojomi/hugo:0.68
  volumes:
    - ./:/src
    - ./public:/output
  environment:
    - HUGO_BASEURL=localhost.lan
    - HUGO_WATCH=true
    - HUGO_THEME=academic
    - HUGO_REFRESH_TIME=3600
    # - HUGO_DESTINATION="/output"
  restart: unless-stopped
  ports:
    - "1313:1313"
